import Providers from "@/components/Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { FC, ReactNode } from "react";
import AppBar from "@/components/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppBar/>
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
